runtime: php81

handlers:
  - url: /(.+\.(gif|png|jpg|css|js))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js)$

  - url: /.*
    script: auto

env_variables:
  # Establece el entorno de CodeIgniter
  CI_ENVIRONMENT: "production"

  # Habilita el uso de Memcache
  GAE_USE_MEMCACHE: "1"

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

inbound_services:
  - warmup